### ISSUE TITLE
Compatibility issue with spiral/testing 2.6.2 causing fatal error in database-seeder

### ISSUE THREAD

**Issue by Shamilius** [spiral-packages/database-seeder#30]
## Description
A fatal error occurs when using `spiral-packages/database-seeder` at version 2.4.0 with `spiral/testing` at version 2.6.2. The error does not occur when `spiral/testing` is downgraded to version 2.5.0.

## Error Message
Fatal error: Access level to Spiral\DatabaseSeeder\TestCase::setUpTraits() must be protected (as in class Spiral\Testing\TestCase) or weaker in /app/vendor/spiral-packages/database-seeder/src/TestCase.php on line 27

## Environment
- **Operating System**: WSL
- **PHP Version**: 8.2
- **spiral-packages/database-seeder Version**: 2.4.0
- **spiral/testing Version**: 2.6.2

## Steps to Reproduce
1. Install `spiral-packages/database-seeder` at version 2.4.0.
2. Install `spiral/testing` at version 2.6.2.
3. Run any test that utilizes the `Spiral\DatabaseSeeder\TestCase`.
4. Observe the fatal error.

## Expected Behavior
The `spiral-packages/database-seeder` should work seamlessly with `spiral/testing` at any version, including 2.6.2, without causing a fatal error.

## Actual Behavior
A fatal error occurs when using the specified versions together, which does not happen with the older version of `spiral/testing` (2.5.0).

## Additional Information
- The issue seems to be related to the visibility of `setUpTraits` method in `TestCase.php`.
- This issue is blocking the upgrade to the latest `spiral/testing` version.

Please let me know if there is any additional information I can provide to help resolve this issue. Thank you for your attention to this matter.

**Comment by S1lentAvenger** [comment]
I confirm the problem, it is reproduced for me.

**Comment by Shamilius** [comment]
Resolved with release v3.1.0
